services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                VITE_APP_NAME: "Simple Blog"
        command: >
            sh -c "php artisan migrate --force &&
                  php artisan key:generate &&
                  php artisan db:seed --force &&
                  php artisan config:cache &&
                  php artisan route:cache &&
                  php artisan event:cache &&
                  php artisan view:cache &&
                  php artisan octane:frankenphp --host=0.0.0.0 --port=80"
        environment:
            - APP_NAME="Simple Blog"
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_TIMEZONE=UTC
            - APP_URL=http://localhost
            - APP_LOCALE=en
            - APP_FALLBACK_LOCALE=en
            - APP_FAKER_LOCALE=en_US
            - APP_MAINTENANCE_DRIVER=file
            - BCRYPT_ROUNDS=12
            - LOG_CHANNEL=stack
            - LOG_STACK=single
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            - DB_CONNECTION=mariadb
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_DATABASE=blog
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - SESSION_DRIVER=database
            - SESSION_LIFETIME=120
            - SESSION_ENCRYPT=false
            - SESSION_PATH=/
            - SESSION_DOMAIN=null
            - CACHE_STORE=database
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost/up" ]
            interval: 5s
            retries: 5
        ports:
            - "8000:80"
        depends_on:
            mariadb:
                condition: service_healthy

    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=root
            - MARIADB_DATABASE=blog
        healthcheck:
            test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
            interval: 10s
            timeout: 5s
            retries: 3
